<!DOCTYPE html>
<!-- 异常隐式拒绝一个promise -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>
<script src="./utils.js"></script>
<script>
    const promise = new Promise((resolve, reject) => {
        // 如果在处理promise时出现未处理的异常，则会被隐式地拒绝
        underclaredVariable++;
    })

    promise.then(() => fail("Happy path,won't be called!"))
        .catch(error => report("Third promise was also rejected"));
</script>

</html>